
package Dialogos;

import Conexion.Conector;
import Conexion.ExeSql;
import Formularios.fmMain;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author David Alcaman
 */
public class jdLogin extends javax.swing.JDialog {
    int Logeado=0;   
    /**
     * Creates new form jdLogin
     * 
     */
    public jdLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        chbInternet.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txUsuario = new javax.swing.JTextField();
        btAceptar = new javax.swing.JButton();
        txClave = new javax.swing.JPasswordField();
        chbInternet = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Identificación");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Usuario");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Clave");

        txUsuario.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        txUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txUsuarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txUsuarioKeyReleased(evt);
            }
        });

        btAceptar.setText("Aceptar");
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });

        txClave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txClaveKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txClaveKeyTyped(evt);
            }
        });

        chbInternet.setText("Me conecto por Internet");

        jButton1.setBackground(new java.awt.Color(217, 153, 75));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/personal2.png"))); // NOI18N
        jLabel3.setToolTipText("");
        jLabel3.setAlignmentY(0.0F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txClave, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbInternet)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAceptar))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbInternet))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
        ResultSet Rs;
        
        String q = "";
        try {
            
            fmMain.SetUsuario("", txUsuario.getText().trim() , txClave.getText(),chbInternet.isSelected(), false,false,false,false,false,false,false,0,0,0,0);
                        
            
            Conector Con = new Conector();
            
            if(Con.getConnection() != null){
                
                ExeSql Sql = new ExeSql();
                ExeSql Sql2 = new ExeSql();  
                System.out.println("Login Correcto");
               
                Rs = Sql.Select("SELECT p.nombre,p.usuario,a.administrador,a.ajuste,a.cobranza,a.gastos,\n" +
                                "a.transformacion,a.adminocp,a.bodega,cc.ccosto,p.rut,u.nivel,u.admin_bodega\n" +      //se agregó campo "nivel"        
                                "FROM personal p\n" +                                                                 //a la consulta SQL
                                "LEFT JOIN pacceso a ON p.rut=a.rut \n" +
                                "LEFT JOIN personal_ccostos cc ON p.rut=cc.rut\n" + 
                                "LEFT JOIN usuario u ON u.usuario=p.usuario\n" + 
                                "WHERE p.usuario='" + txUsuario.getText() + "'");
                Rs.next();
                fmMain.SetUsuario( Rs.getString("nombre").trim(), 
                                  Rs.getString("usuario"),
                                  txClave.getText().trim(),
                                  chbInternet.isSelected(),
                                  Rs.getBoolean("administrador"),
                                  Rs.getBoolean("ajuste"),
                                  Rs.getBoolean("cobranza"),
                                  Rs.getBoolean("gastos"),
                                  Rs.getBoolean("transformacion"),
                                  Rs.getBoolean("adminocp"),
                                  Rs.getBoolean("bodega"),
                                  Rs.getInt("ccosto"),
                                  Rs.getInt("rut"), 
                                  Rs.getInt("nivel"),   //Se agregó campo "nivel" como parámetro
                                  Rs.getInt("admin_bodega") );
                Logeado=1;
                
               
                dispose();
            
            }else{
             
                if(Con.GetError().equals("Conexión rechazada"))
                    fmMain.Mensaje("Error de Comunicación");
            }
            
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Usuario o clave incorrecta 2");
        }

    }//GEN-LAST:event_btAceptarActionPerformed

    private void txUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txUsuarioKeyReleased
         txUsuario.setText(txUsuario.getText().toUpperCase());
    }//GEN-LAST:event_txUsuarioKeyReleased

    private void txClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txClaveKeyTyped
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btAceptar.doClick();
        }
    }//GEN-LAST:event_txClaveKeyTyped

    private void txUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txUsuarioKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            txClave.requestFocus();
        }
    }//GEN-LAST:event_txUsuarioKeyPressed

    private void txClaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txClaveKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btAceptar.doClick();
        }        
    }//GEN-LAST:event_txClaveKeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if(Logeado==0) System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       chbInternet.setVisible(!chbInternet.isVisible());
    }//GEN-LAST:event_jButton1ActionPerformed

    static public String convertToSHA1(String stringToHash) throws UnsupportedEncodingException{
        
        try{
                       
            MessageDigest md = MessageDigest.getInstance("SHA-1");
            byte[] sha1Hash = new byte[40];
            md.update(stringToHash.getBytes("iso-8859-1"),0, stringToHash.length());
            sha1Hash = md.digest();
            StringBuffer buf =  new StringBuffer();
            
            for(int i = 0; i < sha1Hash.length; i++){
                
                int halfbyte = (sha1Hash[i] >>> 4) & 0x0F;
                int two_halfs = 0;
              
                do{
                    if((0 <= halfbyte) && (halfbyte <=9)){
                        buf.append((char) ('0'+halfbyte));
                    }else{
                        buf.append((char)('a'+(halfbyte-10)));
                    }
                       halfbyte = sha1Hash[i] & 0x0F;
                }while(two_halfs++ < 1);
            }
            return buf.toString();
        
        }catch(NoSuchAlgorithmException nsae){
                        System.out.println("No se encontró el algoritmo");
                        System.out.println("===========================");
                        nsae.printStackTrace();
        }catch(UnsupportedEncodingException uee){      
                        System.out.println("Tipo de codificación no encontrado");
                        System.out.println("===========================");
                        uee.printStackTrace();
        }
        return "";
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdLogin dialog = new jdLogin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAceptar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chbInternet;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txClave;
    private javax.swing.JTextField txUsuario;
    // End of variables declaration//GEN-END:variables
}
